### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ChengsongLu** [chenshine1/oms-Diffusion#5]
(oms) lcs@lcs:~/oms-Diffusion$ python inference.py --cloth_path assets/t1.png --model_path assets/m1.png
Loading pipeline components...: 100%|█████████████| 5/5 [00:00<00:00,  7.40it/s]
Traceback (most recent call last):
  File "/home/lcs/oms-Diffusion/inference.py", line 32, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device)
  File "/home/lcs/oms-Diffusion/garment_adapter/garment_diffusion.py", line 93, in __init__
    with safe_open(ref_path, framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by chenshine1** [comment]
model_path is checkpoint path，not human path， inference.py only support generating image with the cloth. If you want to fit certain person, please try another controlnet_inpaiting.py

**Comment by ChengsongLu** [comment]
(oms) lcs@lcs:~/OpenDCO/oms-Diffusion$ python inference.py --cloth_path assets/t1.png --model_path checkpoints/oms_diffusion_100000.safetensors
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 5/5 [00:00<00:00,  8.30it/s]
----checkpoints loaded from path: checkpoints/cloth_segm.pth----
/home/lcs/anaconda3/envs/oms/lib/python3.10/site-packages/torch/nn/functional.py:3737: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.06it/s]
Traceback (most recent call last):
  File "/home/lcs/OpenDCO/oms-Diffusion/inference.py", line 35, in <module>
    image.save(os.path.join(output_path, "out_" + str(i) + ".png"))
AttributeError: 'list' object has no attribute 'save'

**Comment by chenshine1** [comment]
sorry for make a stupid mistake.  please update the  inference.py

**Comment by ChengsongLu** [comment]
It works fine now, thanks. Can you please post a detailed instructions about how to fit a specified person?

**Comment by WilTay1** [comment]
> It works fine now, thanks. Can you please post a detailed instructions about how to fit a specified person?

Yes, please.

**Comment by chenshine1** [comment]
turn to our another project https://github.com/levihsu/OOTDiffusion or find details in controlnet_inpaiting.py, you need to upload a model image and an inpaiting area image like 
![00013_00](https://github.com/chenshine1/oms-Diffusion/assets/16463912/b6c48d9f-401e-46c2-a0b6-8feec7f2ed78)
![00013_00](https://github.com/chenshine1/oms-Diffusion/assets/16463912/cb11b059-9ab7-48bf-aa08-afb6c96ab4fc)
