### ISSUE TITLE
Train another model

### ISSUE THREAD

**Issue by chaincrafter** [chenshine1/oms-Diffusion#6]
Hello, can you release training code? I want to train male models. this only supports woman...

**Comment by chenshine1** [comment]
change the default prompt to “a photography of a man” may help you.

**Comment by chaincrafter** [comment]
This does not work. Where did you fork this repo from?

**Comment by chenshine1** [comment]
you can try another seed. cause the model is trained only on woman model, sometimes it may prefer to generate female image. By the way, it's our own project, the training code will be released after all of the to-do-list are done.

**Comment by xpluscal** [comment]
Hey @ShineChen1024 awesome work, love the model!
I am having the same issue with male, tried some of the DressCode models but the results are generally less accurate.

Any updates on plans for making the model adhere to male a bit better?

I've tried adding male words to prompts and add negative prompts for female etc but not getting a lot better results.

Thank you!
